name: FastApi CD

on:
  push:
    branches:
      - 'main'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run test_app.py
        run: pytest

      - name: black
        run: black --check --diff --line-length 79 .

      - name: isort
        run: isort --check-only --diff --profile black .

      - name: flake8
        run: |
          flake8 app
          flake8 tests

      - name: mypy
        run: |
          mypy app
          mypy tests

  deploy:
    needs: [ run_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: install fabric
        run: |
          pip install fabric==3.2.2
          pip install paramiko==3.5.0

      - name: deploy
        env:
          P_SSH_KEY: ${{ secrets.P_SSH_KEY }}
        run: |
          echo $P_SSH_KEY
          python fabfile.py
          fab deploy