name: FastApi CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
#  run_tests:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: setup python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.12
#
#      - name: print(login)
#        run: echo ${{ secrets.TEST_KEY }}
#
#      - name: install dependencies
#        run: pip install -r requirements.txt
#
#      - name: run test_app.py
#        run: pytest
#
#      - name: black
#        run: black --check --diff --line-length 79 .
#
#      - name: isort
#        run: isort --check-only --diff --profile black .
#
#      - name: flake8
#        run: |
#          flake8 app
#          flake8 tests
#
##      - name: mypy
##        run: |
##          mypy app
##          mypy tests
#
#  build_and_pub:
#    needs: [run_tests]
#    runs-on: ubuntu-latest
#    env:
#      LOGIN: ${{ secrets.DOCKER_LOGIN }}
#      PWD: ${{ secrets.DOCKER_PWD }}
#      NAME: ${{ secrets.DOCKER_NAME }}
#
#
#    steps:
#      - name: checkout code
#        uses: actions/checkout@v2
#
#      - name: login to docker
#        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
#
#      - name: build image
#        run: |
#          echo ${GITHUB_REF}
#          echo ${GITHUB_REF:11}
#          echo ${GITHUB_REF:5}
#          echo ${GITHUB_REF:15}
#          docker build -t $LOGIN/$NAME:3.0.0 .
#
#      - name: push image to docker
#        run: docker push $LOGIN/$NAME:3.0.0

  deploy:
#    needs: [build_and_pub]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: install fabric
        run: |
          pip install fabric==3.2.2
          pip install paramiko==3.5.0

      - name: deploy
        env:
          P_SSH_KEY: ${{ secrets.P_SSH_KEY }}
        run: |
          echo $P_SSH_KEY
#          fab deploy


